// react/src/components/Board.js
import { useEffect, useState } from 'react'
import { FICHA_O, FICHA_X, FICHA_NONE, winsArray } from '../tools/constants'

export default function Board() {
    const [user, setUser] = useState(FICHA_X)
    const [positions, setPositions] = useState(Array(9).fill(FICHA_NONE))
    const [winner, setWinner] = useState(0)

    useEffect(()=>{
        winsArray.forEach( line => {
            const [p1, p2, p3] = line
            console.log(p1, p2, p3)
            const row = positions.filter( (tag, index) => (index===p1 || index===p2 || index===p3) )
            console.log(row)
            if( !row.map( tag => tag===FICHA_O ).includes(false) ) {
                setWinner( prev => FICHA_O );
            }
            if( !row.map( tag => tag===FICHA_X ).includes(false) ) {
                setWinner( prev => FICHA_X );
            }
            if( !positions.includes( 0 ) ) {
                setWinner( 3 )
            }
        })
    },[positions])

    const setTag = (index) => {
        if( positions[ index ]===0 ) {
            setPositions( prev => prev.toSpliced(index, 1, user) )
            if( winner===0 ) {
              if( user === FICHA_X ) setUser( prev => FICHA_O )
              else setUser( prev => FICHA_X)
            }
        }
    }

    const renderTag = ( userId ) => {
        switch( userId ) {
            case FICHA_X: return "X";
            case FICHA_O: return "O";
            default: return "";
        }
    }

    const reset = () => {
        setWinner( prev => 0 )
        setUser( prev => FICHA_X )
        setPositions( Array(9).fill(0) )
    }

    return <div className="flex flex-col gap-2 p-2 mx-auto w-fit">
        <div className="flex flex-row gap-3">
            <div onClick={()=>setTag( 0 )}  className="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{ renderTag( positions[0] ) }</div>
            <div onClick={()=>setTag( 1 )}  className="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{ renderTag( positions[1] ) }</div>
            <div onClick={()=>setTag( 2 )}  className="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{ renderTag( positions[2] ) }</div>
        </div>
        <div className="flex flex-row gap-3">
            <div onClick={()=>setTag( 3 )}  className="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer" >{ renderTag( positions[3] ) }</div>
            <div onClick={()=>setTag( 4 )}  className="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer" >{ renderTag( positions[4] ) }</div>
            <div onClick={()=>setTag( 5 )}  className="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer" >{ renderTag( positions[5] ) }</div>
        </div>
        <div className="flex flex-row gap-3">
            <div onClick={()=>setTag( 6 )}  className="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{ renderTag( positions[6] ) }</div>
            <div onClick={()=>setTag( 7 )}  className="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{ renderTag( positions[7] ) }</div>
            <div onClick={()=>setTag( 8 )}  className="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{ renderTag( positions[8] ) }</div>
        </div>
        { winner!==0 && <div className="absolute w-[450px] h-[450px] m-3 flex justify-center items-center text-[2rem] bg-[#050505dd] text-purple-700 shadow-lg rounded-lg cursor-pointer" onClick={()=>reset()}>
            { winner===1 && <span>Ganó Jugador X</span>}
            { winner===2 && <span>Ganó Jugador O</span>}
            { winner===3 && <span>No hay ganador</span>}
        </div>}
    </div>

}

// angular/src/app/board/board.component.ts
import { Component } from '@angular/core';

const winsArray = [
  [0,1,2],
  [0,4,8],
  [0,3,6],
  [1,4,7],
  [2,4,6],
  [2,5,8],
  [3,4,5],
  [6,4,2],
  [6,7,8]
]
const USER_X = 1
const USER_O = 2

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html',
  styleUrls: ['./board.component.css']
})
export class BoardComponent {

  winner:number = 0;
  user:number = USER_X
  positions:Array<number> = Array(9).fill(0)

  setTag( index:number ){
    if( this.positions[ index]==0 ) {
      this.positions[ index ] = this.user
      this.check()
      if( this.winner==0 ) {
        if( this.user === USER_X ) this.user = USER_O
        else this.user = USER_X
      }
      if( !this.positions.includes( 0 ) ) {
        this.winner = 3
      }
    }
  }

  renderTag( value:number ): string {
    switch( value ) {
      case USER_X: return "X";
      case USER_O: return "O";
      default: return "";
    }
  }

  check() {
    winsArray.forEach( line => {
      const [p1, p2, p3] = line
      const row = this.positions.filter( (tag, index) => (index==p1 || index==p2 || index==p3) )
      if( !row.map( tag => tag===this.user ).includes(false) ) {
        this.winner = this.user;
        return
      }
    })
  }

  reset(){
    this.winner = 0
    this.user = USER_X
    this.positions = Array(9).fill(0)
  }

}

<div class="flex flex-col gap-2 p-2 mx-auto w-fit">
    <div class="flex flex-row gap-3">
        <div (click)="setTag( 0 )"  class="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{{ renderTag( positions[0] ) }}</div>
        <div (click)="setTag( 1 )"  class="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{{ renderTag( positions[1] ) }}</div>
        <div (click)="setTag( 2 )"  class="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{{ renderTag( positions[2] ) }}</div>
    </div>
    <div class="flex flex-row gap-3">
        <div (click)="setTag( 3 )"  class="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer" >{{ renderTag( positions[3] ) }}</div>
        <div (click)="setTag( 4 )"  class="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer" >{{ renderTag( positions[4] ) }}</div>
        <div (click)="setTag( 5 )"  class="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer" >{{ renderTag( positions[5] ) }}</div>
    </div>
    <div class="flex flex-row gap-3">
        <div (click)="setTag( 6 )"  class="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{{ renderTag( positions[6] ) }}</div>
        <div (click)="setTag( 7 )"  class="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{{ renderTag( positions[7] ) }}</div>
        <div (click)="setTag( 8 )"  class="shadow-purple-950 shadow-md hover:shadow text-[4rem] flex justify-center items-center w-[150px] h-[150px] border border-purple-700 p-2 hover:bg-purple-950 text-purple-700 hover:text-black font-bold cursor-pointer">{{ renderTag( positions[8] ) }}</div>
    </div>
    <div *ngIf="winner!=0" class="absolute w-[450px] h-[450px] m-3 flex justify-center items-center text-[2rem] bg-[#050505dd] text-purple-700 shadow-lg rounded-lg cursor-pointer" (click)="reset()">
        <span *ngIf="winner==1">Ganó Jugador X</span>
        <span *ngIf="winner==2">Ganó Jugador O</span>
        <span *ngIf="winner==3">No hay ganador</span>
    </div>
</div>
